# Spring boot global configuration
spring:
  output:
    ansi:
      enabled: ALWAYS

# Custom 'killrvideo' keys App
killrvideo:

  application: 
    name: killrvideo
    instance: 
      id: 0
    
  cassandra:
    clustername: killrvideo
    mutation-error-log: /tmp/killrvideo-mutation-errors.log
    maxNumberOfTries: 10
    delayBetweenTries: 2

  search:
    ignoredWords: and,or,but,nor,so,for,yet,after,as,till,to,the,at,in,not,now,of,if,this,an,are,all,about,along,by,is,it,on,why,be,can,com,get,out,see,some,new,these,that,thing,things,wish,known,say,they,had,here,like,live,let,do,with,what,when,www,watch,will,http,https,us,you,your,more,his,her,they,them,their,me,we,near,bit,ly,back,meet,know,key,video,various,find,only,from,kind,channel,comments,below,check,right,full,while,gets,up,each,no,buy,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z

  graph:
    timeout: 3000
    recommendation.name: killrvideo_video_recommendations
    
  ssl:
    enable: false
    CACertFileLocation: cassandra.cert
    
  grpc-server: 
    port: 8899
  
  kafka:
    server: localhost:9092
    ack: 1
    consumerGroup: killrvideo
     
  etcd:
    host: 10.0.75.1
    port: 2379
    maxNumberOfTries: 30
    delayBetweenTries: 5
    
  threadpool:
    minThreads: 5
    maxThreads: 10
    ttlThreads: 60
    queueSize: 1000  